import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from '@mui/material/CssBaseline';
import { ApolloWrapper } from "./ApolloWrapper";
import theme from "@/themes";
import Navbar from "@/common/Navbar";
import Footer from "@/common/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Music application",
  description: "music playear Generated by create next app",
};

const RootLayout = ({ children, }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <ApolloWrapper>
                <Navbar />
                {children}
                <Footer />
              </ApolloWrapper>
            </ThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}

export default RootLayout;